import { Category, Pricing, AITool } from './App';

export const TOOLS_DATA: AITool[] = [
  // Chat AI
  { 
    id: 'chatgpt', 
    name: 'ChatGPT', 
    description: 'Advanced conversational AI by OpenAI capable of text generation, coding, and reasoning.', 
    category: 'Chat AI', 
    pricing: 'Freemium', 
    pricingDetails: 'Free / $20 per month for Plus',
    url: 'https://chat.openai.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    features: ['Text Generation', 'Code Assistance', 'Image Creation (DALL-E)', 'Voice Mode', 'Custom GPTs'],
    pros: ['Highly versatile', 'Large knowledge base', 'Excellent reasoning capabilities'],
    cons: ['Occasional hallucinations', 'Knowledge cutoff', 'Premium features require subscription'],
    useCases: ['Content Creation', 'Code Debugging', 'Learning & Tutoring', 'Brainstorming'],
    videoUrl: 'https://www.youtube.com/watch?v=OsL66Y-O-64',
    isVerified: true,
    hasDeals: false,
    tags: ['LLM', 'Assistant', 'OpenAI'],
    rating: 4.9,
    reviewCount: 12500,
    popularity: 100,
    addedDate: '2022-11-30'
  },
  { 
    id: 'gemini', 
    name: 'Google Gemini', 
    description: 'Googles most capable AI model, integrated across Google Workspace and search.', 
    category: 'Chat AI', 
    pricing: 'Freemium', 
    pricingDetails: 'Free / $20 per month for Advanced',
    url: 'https://gemini.google.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Google_Gemini_logo.svg',
    features: ['Multimodal reasoning', 'Google Workspace integration', 'Real-time search access', 'Large context window'],
    pros: ['Fast response times', 'Deep Google ecosystem integration', 'Excellent at summarizing long docs'],
    cons: ['Interface can be cluttered', 'Inconsistent formatting at times'],
    useCases: ['Email Drafting', 'Data Extraction from Drive', 'Travel Planning', 'YouTube Video Summarization'],
    videoUrl: 'https://www.youtube.com/watch?v=UI8Z_f8X0vY',
    isVerified: true,
    hasDeals: false,
    tags: ['Google', 'Multimodal', 'Workspace'],
    rating: 4.7,
    reviewCount: 8200,
    popularity: 100,
    addedDate: '2023-03-21'
  },
  { 
    id: 'claude', 
    name: 'Claude', 
    description: 'Anthropic\'s AI assistant focused on being helpful, harmless, and honest with a large context window.', 
    category: 'Chat AI', 
    pricing: 'Freemium', 
    pricingDetails: 'Free / $20 per month for Pro',
    url: 'https://claude.ai', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Claude_AI_logo.svg',
    features: ['Large context window (200k+)', 'Artifacts for code/docs', 'High safety standards', 'Nuanced writing style'],
    pros: ['More "human" writing style', 'Excellent at complex coding tasks', 'Very low hallucination rate'],
    cons: ['Strict safety filters can be overactive', 'No built-in image generation'],
    useCases: ['Academic Research', 'Long-form Writing', 'Complex Coding', 'Legal Document Review'],
    videoUrl: 'https://www.youtube.com/watch?v=fS_65692A7Y',
    isVerified: true,
    hasDeals: false,
    tags: ['Safety', 'Large Context', 'Writing'],
    rating: 4.8,
    reviewCount: 5400,
    popularity: 100,
    addedDate: '2023-03-14'
  },
  { id: 'copilot', name: 'Microsoft Copilot', description: 'AI-powered companion for the web, integrated into Windows and Microsoft 365.', category: 'Chat AI', pricing: 'Freemium', url: 'https://copilot.microsoft.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Microsoft_Copilot_logo.svg', features: ['GPT-4 access for free', 'DALL-E 3 image generation', 'Web search integration', 'Microsoft 365 integration', 'Sidebar in Edge browser'], pros: ['Free access to GPT-4', 'Excellent web search capabilities', 'Seamless Windows integration'], cons: ['Can be slower than ChatGPT', 'Strict conversation limits in free tier', 'Interface can feel cluttered'], rating: 4.6, reviewCount: 7100, popularity: 100, addedDate: '2023-02-07' },
  { id: 'pi', name: 'Pi', description: 'A personal AI assistant by Inflection AI designed to be supportive, smart, and available anytime.', category: 'Chat AI', pricing: 'Free', url: 'https://pi.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Inflection_AI_Logo.png', features: ['Empathetic conversation', 'Voice interaction', 'Personalized coaching', 'Cross-platform sync'], pros: ['Very natural conversational tone', 'Great for emotional support', 'Completely free to use'], cons: ['Not as good at technical tasks', 'Limited third-party integrations', 'Knowledge base can be outdated'], rating: 4.5, reviewCount: 3200, popularity: 75, addedDate: '2023-05-02' },
  { id: 'grok', name: 'Grok', description: 'AI developed by xAI with real-time access to the world via the X platform.', category: 'Chat AI', pricing: 'Paid', url: 'https://x.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/57/X_logo_2023_%28white%29.svg', features: ['Real-time X data access', 'Witty/rebellious personality', 'Large context window', 'Direct integration with X'], pros: ['Up-to-the-minute news access', 'Unique, less "filtered" personality', 'Strong reasoning capabilities'], cons: ['Requires X Premium subscription', 'Can be overly sarcastic', 'Smaller developer ecosystem'], rating: 4.4, reviewCount: 4500, popularity: 82, addedDate: '2023-11-04' },
  { id: 'poe', name: 'Poe', description: 'Quora\'s platform to access various AI models like GPT-4, Claude, and specialized bots in one place.', category: 'Chat AI', pricing: 'Freemium', url: 'https://poe.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Poe_Logo.png', features: ['Multi-model access', 'Bot creation tools', 'Fast mobile app', 'Cross-platform sync'], pros: ['Access many models in one UI', 'Easy to create custom bots', 'Great mobile experience'], cons: ['Compute point system can be confusing', 'Premium is relatively expensive', 'Limited advanced features for some models'], rating: 4.7, reviewCount: 2800, popularity: 85, addedDate: '2023-02-01' },
  { id: 'huggingchat', name: 'HuggingChat', description: 'Open-source chat interface by Hugging Face using the latest open-source LLMs.', category: 'Chat AI', pricing: 'Free', url: 'https://huggingface.co/chat', logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Hugging_Face_logo.svg', features: ['Open-source models (Llama, Mistral)', 'Web search integration', 'Customizable system prompts', 'Privacy-focused'], pros: ['Completely free and open', 'Access to cutting-edge OS models', 'No data tracking for training'], cons: ['Performance depends on model used', 'Can be less stable than commercial apps', 'Fewer "quality of life" features'], rating: 4.5, reviewCount: 1200, popularity: 70, addedDate: '2023-04-25' },
  { id: 'character-ai', name: 'Character.ai', description: 'Create and chat with fictional, historical, or celebrity-based AI characters.', category: 'Chat AI', pricing: 'Freemium', url: 'https://character.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Character.ai_logo.png', features: ['Roleplay with characters', 'Group chats', 'Character creation engine', 'Voice mode'], pros: ['Incredible for creative writing', 'Massive library of user bots', 'Highly engaging and fun'], cons: ['Strict NSFW filters', 'Memory can be inconsistent', 'Not for factual or technical help'], rating: 4.8, reviewCount: 9800, popularity: 92, addedDate: '2022-09-16' },
  { id: 'you-chat', name: 'YouChat', description: 'AI search assistant integrated into You.com that provides direct answers and citations.', category: 'Chat AI', pricing: 'Free', url: 'https://you.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/You.com_logo.svg', rating: 4.3, reviewCount: 850, popularity: 65, addedDate: '2022-12-23' },
  { id: 'replika', name: 'Replika', description: 'An AI companion that learns from you and provides emotional support and conversation.', category: 'Chat AI', pricing: 'Freemium', url: 'https://replika.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Replika_Logo.png', rating: 4.2, reviewCount: 15600, popularity: 80, addedDate: '2017-03-13' },
  { id: 'koalachat', name: 'KoalaChat', description: 'AI writer and chat assistant optimized for SEO and content creators.', category: 'Chat AI', pricing: 'Freemium', url: 'https://koala.sh/chat', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Koala_AI_Logo.png', rating: 4.4, reviewCount: 420, popularity: 60, addedDate: '2023-03-01' },
  { id: 'chatsonic', name: 'ChatSonic', description: 'AI chat assistant by Writesonic with real-time Google search integration and image generation.', category: 'Chat AI', pricing: 'Freemium', url: 'https://writesonic.com/chat', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Writesonic_Logo.png', rating: 4.5, reviewCount: 2100, popularity: 78, addedDate: '2022-12-15' },
  { id: 'monica', name: 'Monica', description: 'All-in-one AI browser extension for chatting, reading, and writing across the web.', category: 'Chat AI', pricing: 'Freemium', url: 'https://monica.im', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Monica_AI_Logo.png', rating: 4.6, reviewCount: 1800, popularity: 72, addedDate: '2023-01-20' },
  { id: 'merlin', name: 'Merlin', description: 'AI assistant extension that helps you summarize videos, write emails, and chat with websites.', category: 'Chat AI', pricing: 'Freemium', url: 'https://getmerlin.in', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Merlin_AI_Logo.png', rating: 4.5, reviewCount: 1500, popularity: 68, addedDate: '2023-02-10' },
  { id: 'sider', name: 'Sider', description: 'AI sidebar for your browser that integrates ChatGPT, Claude, and Gemini into your workflow.', category: 'Chat AI', pricing: 'Freemium', url: 'https://sider.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Sider_AI_Logo.png', rating: 4.7, reviewCount: 2300, popularity: 74, addedDate: '2023-03-15' },

  // Image Generation
  { 
    id: 'midjourney', 
    name: 'Midjourney', 
    description: 'High-quality artistic image generation known for its unique aesthetic and Discord-based interface.', 
    category: 'Image Generation', 
    pricing: 'Paid', 
    pricingDetails: 'Starts at $10 per month',
    url: 'https://www.midjourney.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png',
    features: ['High-fidelity artistic generation', 'Vary Region (Inpainting)', 'Style Tuner', 'Discord-based community', 'Web interface (Alpha)'],
    pros: ['Industry-leading aesthetic quality', 'Strong community support', 'Excellent lighting and texture'],
    cons: ['No free tier', 'Discord interface can be intimidating', 'Copyright ownership complexity'],
    useCases: ['Concept Art', 'Logo Design', 'Photorealistic Mockups', 'Social Media Graphics'],
    videoUrl: 'https://www.youtube.com/watch?v=R_f9X_oP6mY',
    isVerified: true,
    hasDeals: true,
    tags: ['Art', 'Discord', 'High Quality'],
    rating: 4.9,
    reviewCount: 15400,
    popularity: 100,
    addedDate: '2022-07-12'
  },
  { id: 'dalle', name: 'DALL·E', description: 'OpenAI\'s image generation system that creates realistic images and art from text descriptions.', category: 'Image Generation', pricing: 'Paid', url: 'https://openai.com/dall-e-3', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg', features: ['Prompt adherence', 'In-chat editing', 'Aspect ratio control', 'Safety guardrails'], pros: ['Unmatched prompt following', 'Easy to use via ChatGPT', 'Consistent quality'], cons: ['Limited artistic control', 'Can feel "over-polished"', 'No local execution'], rating: 4.8, reviewCount: 12100, popularity: 100, addedDate: '2021-01-05' },
  { id: 'stable-diffusion', name: 'Stable Diffusion', description: 'Open-source latent text-to-image diffusion model capable of generating photo-realistic images.', category: 'Image Generation', pricing: 'Free', url: 'https://stability.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Stability_AI_logo.svg', features: ['Local execution', 'ControlNet support', 'LoRA training', 'Inpainting/Outpainting'], pros: ['Completely free and private', 'Infinite customization', 'Large open-source community'], cons: ['High hardware requirements', 'Steep learning curve', 'Interface depends on third-party tools'], rating: 4.7, reviewCount: 25000, popularity: 100, addedDate: '2022-08-22' },
  { id: 'leonardo', name: 'Leonardo AI', description: 'Generative AI platform for creators, offering fine-tuned models for various artistic styles.', category: 'Image Generation', pricing: 'Freemium', url: 'https://leonardo.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Leonardo_AI_Logo.png', features: ['Fine-tuned models', 'Canvas editor', 'Motion generation', 'Texture generation'], pros: ['Excellent web interface', 'Great for game assets', 'Generous daily free credits'], cons: ['Can be overwhelming for beginners', 'Some models are credit-heavy', 'Artistic style can be repetitive'], rating: 4.8, reviewCount: 8900, popularity: 88, addedDate: '2022-12-01' },
  { id: 'firefly', name: 'Adobe Firefly', description: 'Adobe\'s family of creative generative AI models, integrated directly into Photoshop and Illustrator.', category: 'Image Generation', pricing: 'Freemium', url: 'https://www.adobe.com/firefly', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Adobe_Firefly_logo.svg', features: ['Generative Fill', 'Text Effects', 'Generative Recolor', 'Commercial safety'], pros: ['Seamless Adobe workflow', 'Trained on licensed content', 'Very easy to use'], cons: ['Limited standalone features', 'Requires Adobe subscription for full use', 'Less "creative" than Midjourney'], rating: 4.7, reviewCount: 6300, popularity: 100, addedDate: '2023-03-21' },
  { id: 'recraft', name: 'Recraft', description: 'Infinite canvas for generating and editing vector art, icons, and 3D illustrations.', category: 'Design AI', pricing: 'Freemium', url: 'https://www.recraft.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Recraft_AI_Logo.png', rating: 4.6, reviewCount: 1200, popularity: 70, addedDate: '2023-05-10' },
  { id: 'canva-magic', name: 'Canva AI', description: 'AI image and video generator integrated directly into the Canva design platform.', category: 'Image Generation', pricing: 'Freemium', url: 'https://www.canva.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg', features: ['Text-to-image', 'Text-to-video', 'Magic Eraser', 'Magic Edit'], pros: ['Integrated into Canva workflow', 'Very user-friendly', 'Access to millions of assets'], cons: ['Quality not as high as Midjourney', 'Limited advanced settings', 'Video generation is very short'], rating: 4.5, reviewCount: 45000, popularity: 100, addedDate: '2023-09-14' },
  { id: 'playground', name: 'Playground AI', description: 'Easy-to-use online AI image creator that combines real-time editing with powerful models.', category: 'Image Generation', pricing: 'Freemium', url: 'https://playgroundai.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Playground_AI_Logo.png', rating: 4.6, reviewCount: 3400, popularity: 75, addedDate: '2022-11-15' },
  { id: 'nightcafe', name: 'NightCafe', description: 'Community-driven AI art generator with multiple methods including Stable Diffusion and DALL-E.', category: 'Image Generation', pricing: 'Freemium', url: 'https://creator.nightcafe.studio', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/NightCafe_Logo.png', rating: 4.4, reviewCount: 12800, popularity: 82, addedDate: '2019-11-01' },
  { id: 'artbreeder', name: 'Artbreeder', description: 'Collaborative AI tool for creating unique characters and landscapes by "breeding" images.', category: 'Image Generation', pricing: 'Freemium', url: 'https://www.artbreeder.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Artbreeder_Logo.png', rating: 4.3, reviewCount: 5600, popularity: 68, addedDate: '2018-05-01' },
  { id: 'dreamstudio', name: 'DreamStudio', description: 'The official web interface for Stable Diffusion, offering fine-grained control over generation.', category: 'Image Generation', pricing: 'Paid', url: 'https://dreamstudio.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/41/DreamStudio_Logo.png', rating: 4.5, reviewCount: 2100, popularity: 72, addedDate: '2022-08-22' },
  { id: 'deepai', name: 'DeepAI', description: 'Suite of AI tools for image generation, editing, and enhancement via simple APIs.', category: 'Image Generation', pricing: 'Freemium', url: 'https://deepai.org', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/DeepAI_Logo.png', rating: 4.1, reviewCount: 4300, popularity: 60, addedDate: '2016-01-01' },
  { id: 'fotor-ai', name: 'Fotor AI', description: 'Online photo editor with integrated AI tools for image generation and enhancement.', category: 'Image Generation', pricing: 'Freemium', url: 'https://www.fotor.com/features/ai-image-generator/', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Fotor_Logo.png', rating: 4.4, reviewCount: 8900, popularity: 78, addedDate: '2023-02-15' },
  { id: 'pixlr-ai', name: 'Pixlr AI', description: 'Cloud-based photo editing suite with AI-powered generative fill and image creation.', category: 'Image Generation', pricing: 'Freemium', url: 'https://pixlr.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Pixlr_Logo.png', rating: 4.3, reviewCount: 12400, popularity: 74, addedDate: '2023-04-10' },
  { id: 'craiyon', name: 'Craiyon', description: 'Simple and free AI image generator formerly known as DALL-E Mini.', category: 'Image Generation', pricing: 'Free', url: 'https://www.craiyon.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Craiyon_Logo.png', rating: 4.0, reviewCount: 35000, popularity: 85, addedDate: '2022-07-01' },
  { id: 'bluewillow', name: 'BlueWillow', description: 'Discord-based AI image generator similar to Midjourney, offering high-quality results.', category: 'Image Generation', pricing: 'Freemium', url: 'https://www.bluewillow.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/BlueWillow_Logo.png', rating: 4.5, reviewCount: 2800, popularity: 65, addedDate: '2023-01-10' },
  { id: 'krea', name: 'Krea AI', description: 'Real-time AI generation tool for designers, offering high-quality upscaling and enhancement.', category: 'Image Generation', pricing: 'Freemium', url: 'https://www.krea.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Krea_AI_Logo.png', rating: 4.7, reviewCount: 1100, popularity: 62, addedDate: '2023-06-01' },
  { id: 'magnific', name: 'Magnific AI', description: 'The most advanced AI image upscaler and enhancer that adds incredible detail to images.', category: 'Image Generation', pricing: 'Paid', url: 'https://magnific.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Magnific_AI_Logo.png', rating: 4.8, reviewCount: 540, popularity: 58, addedDate: '2023-11-20' },

  // Video AI
  { 
    id: 'runway', 
    name: 'Runway', 
    description: 'Next-generation creative tools for video generation, editing, and real-time collaboration.', 
    category: 'Video AI', 
    pricing: 'Freemium', 
    url: 'https://runwayml.com', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Runway_logo.svg',
    features: ['Gen-2 Text-to-Video', 'Gen-1 Video-to-Video', 'Motion Brush', 'Inpainting', 'Frame Interpolation'],
    pros: ['Cutting-edge video tech', 'Comprehensive editing suite', 'Professional-grade results'],
    cons: ['High credit consumption', 'Steep learning curve', 'Requires powerful hardware for best results'],
    rating: 4.6,
    reviewCount: 12400,
    popularity: 100,
    addedDate: '2021-03-01'
  },
  { id: 'pika', name: 'Pika', description: 'An idea-to-video platform that brings your creativity to life through motion.', category: 'Video AI', pricing: 'Freemium', url: 'https://pika.art', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Pika_Labs_Logo.png', features: ['Text-to-video', 'Image-to-video', 'Lip sync', 'Sound effects generation', 'Area modification'], pros: ['Very high creative control', 'Great for short animations', 'Intuitive web interface'], cons: ['Limited video length', 'Can have flickering artifacts', 'High-res exports require paid plan'], rating: 4.7, reviewCount: 8200, popularity: 100, addedDate: '2023-04-01' },
  { id: 'luma', name: 'Luma Dream Machine', description: 'High-fidelity video generation model that creates realistic and cinematic videos from text and images.', category: 'Video AI', pricing: 'Freemium', url: 'https://lumalabs.ai/dream-machine', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Luma_AI_Logo.png', features: ['Cinematic realism', 'Complex motion handling', 'High-resolution output', 'Consistent characters'], pros: ['Incredible realistic quality', 'Handles physics very well', 'Fast generation times'], cons: ['Limited free generations', 'Strict safety filters', 'Occasional morphing in long shots'], rating: 4.8, reviewCount: 5600, popularity: 80, addedDate: '2024-06-12' },
  { id: 'heygen', name: 'HeyGen', description: 'AI video generation platform for creating professional business videos with talking avatars.', category: 'Video AI', pricing: 'Freemium', url: 'https://www.heygen.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/HeyGen_Logo.png', features: ['Talking avatars', 'Video translation', 'Photo avatars', 'Custom avatar creation'], pros: ['Extremely realistic lip-sync', 'Great for marketing/training', 'Easy to use templates'], cons: ['Expensive for high volume', 'Watermark on free tier', 'Limited background customization'], rating: 4.8, reviewCount: 9200, popularity: 100, addedDate: '2020-11-01' },
  { id: 'synthesia', name: 'Synthesia', description: 'Create professional videos with AI avatars in over 120 languages, perfect for training and marketing.', category: 'Video AI', pricing: 'Paid', url: 'https://www.synthesia.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Synthesia_Logo.png', features: ['140+ AI avatars', '120+ languages', 'Custom avatars', 'AI video assistant'], pros: ['Industry-leading avatar quality', 'Excellent multi-language support', 'Professional editing tools'], cons: ['No free tier', 'Avatars can feel slightly robotic', 'Strict usage policies'], rating: 4.7, reviewCount: 11500, popularity: 100, addedDate: '2017-12-01' },
  { id: 'invideo', name: 'InVideo', description: 'AI-powered video creation tool that turns scripts into professional videos for social media.', category: 'Video AI', pricing: 'Freemium', url: 'https://invideo.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/InVideo_Logo.png', rating: 4.5, reviewCount: 15800, popularity: 84, addedDate: '2017-04-01' },
  { id: 'descript', name: 'Descript', description: 'All-in-one video and podcast editor that makes editing as easy as editing a text document.', category: 'Video AI', pricing: 'Freemium', url: 'https://www.descript.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Descript_Logo.png', features: ['Text-based video editing', 'Overdub (voice cloning)', 'Studio Sound', 'Filler word removal'], pros: ['Revolutionary editing workflow', 'Excellent audio cleanup', 'Great for podcasters'], cons: ['Steep learning curve', 'Can be resource-heavy', 'Transcription isn\'t 100% perfect'], rating: 4.8, reviewCount: 18400, popularity: 86, addedDate: '2017-12-01' },
  { id: 'pictory', name: 'Pictory', description: 'Automatically create short, highly-sharable branded videos from your long-form content.', category: 'Video AI', pricing: 'Freemium', url: 'https://pictory.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Pictory_Logo.png', rating: 4.4, reviewCount: 4200, popularity: 72, addedDate: '2020-07-01' },
  { id: 'fliki', name: 'Fliki', description: 'Turn your blog posts or scripts into videos with realistic AI voices in minutes.', category: 'Video AI', pricing: 'Freemium', url: 'https://fliki.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Fliki_Logo.png', rating: 4.5, reviewCount: 6100, popularity: 78, addedDate: '2022-01-01' },
  { id: 'elai', name: 'Elai.io', description: 'Generate AI videos with human-like avatars from just text for corporate training and sales.', category: 'Video AI', pricing: 'Freemium', url: 'https://elai.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Elai_Logo.png', rating: 4.3, reviewCount: 1200, popularity: 60, addedDate: '2021-05-01' },
  { id: 'colossyan', name: 'Colossyan', description: 'AI video creator for workplace learning, featuring high-quality avatars and localization.', category: 'Video AI', pricing: 'Paid', url: 'https://www.colossyan.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Colossyan_Logo.png', rating: 4.6, reviewCount: 2300, popularity: 65, addedDate: '2020-01-01' },
  { id: 'deepbrain', name: 'DeepBrain AI', description: 'Create realistic AI human videos by simply providing a script, ideal for news and retail.', category: 'Video AI', pricing: 'Paid', url: 'https://www.deepbrain.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/DeepBrain_AI_Logo.png', rating: 4.5, reviewCount: 1800, popularity: 62, addedDate: '2016-01-01' },
  { id: 'kaiber', name: 'Kaiber', description: 'AI creative lab that generates stunning animations and videos from your images and music.', category: 'Video AI', pricing: 'Freemium', url: 'https://kaiber.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Kaiber_Logo.png', rating: 4.7, reviewCount: 8400, popularity: 74, addedDate: '2023-02-01' },
  { id: 'sora', name: 'Sora', description: 'OpenAI\'s groundbreaking text-to-video model that creates highly detailed and realistic scenes.', category: 'Video AI', pricing: 'Paid', url: 'https://openai.com/sora', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg', rating: 4.9, reviewCount: 1500, popularity: 95, addedDate: '2024-02-15' },
  { id: 'vimeo-ai', name: 'Vimeo AI', description: 'Suite of AI tools for video editing, script generation, and automatic highlight creation.', category: 'Video AI', pricing: 'Freemium', url: 'https://vimeo.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Vimeo_Logo.svg', rating: 4.4, reviewCount: 32000, popularity: 80, addedDate: '2023-07-01' },
  { id: 'wonder-dynamics', name: 'Wonder Dynamics', description: 'AI tool that automatically animates, lights, and composes CG characters into live-action scenes.', category: 'Video AI', pricing: 'Paid', url: 'https://wonderdynamics.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Wonder_Dynamics_Logo.png', rating: 4.8, reviewCount: 450, popularity: 55, addedDate: '2023-03-01' },

  // Coding AI
  { 
    id: 'github-copilot', 
    name: 'GitHub Copilot', 
    description: 'AI pair programmer that helps you write code faster with less work.', 
    category: 'Coding AI', 
    pricing: 'Paid', 
    url: 'https://github.com/features/copilot', 
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg',
    features: ['Context-aware code completion', 'Chat in IDE', 'Unit test generation', 'Documentation assistance', 'CLI integration'],
    pros: ['Seamless IDE integration', 'Understands project context', 'Supports 100+ languages'],
    cons: ['Requires subscription', 'Can suggest insecure code patterns', 'Privacy concerns for some enterprises'],
    rating: 4.8,
    reviewCount: 45000,
    popularity: 100,
    addedDate: '2021-10-29'
  },
  { id: 'codeium', name: 'Codeium', description: 'Free AI-powered code acceleration toolkit for individual developers.', category: 'Coding AI', pricing: 'Freemium', url: 'https://codeium.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Codeium_Logo.png', features: ['Autofill code', 'Natural language search', 'Unit test generation', 'Multi-IDE support'], pros: ['Generous free tier for individuals', 'Very fast completions', 'Supports 70+ languages'], cons: ['Enterprise features are paid', 'Can miss complex context', 'Smaller community than Copilot'], rating: 4.7, reviewCount: 12500, popularity: 82, addedDate: '2022-06-01' },
  { id: 'cursor', name: 'Cursor', description: 'The AI-first code editor, built for pair programming with an AI that understands your entire codebase.', category: 'Coding AI', pricing: 'Freemium', url: 'https://cursor.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Cursor_AI_Logo.png', features: ['Whole codebase indexing', 'AI-powered refactoring', 'Chat with your files', 'VS Code extension support'], pros: ['Best-in-class codebase awareness', 'Seamlessly replaces VS Code', 'Powerful "Composer" mode'], cons: ['Requires switching editors', 'Paid plan needed for best models', 'Can be resource-intensive'], rating: 4.9, reviewCount: 8400, popularity: 100, addedDate: '2023-01-01' },
  { id: 'tabnine', name: 'Tabnine', description: 'AI assistant for software developers that provides private and secure code completions.', category: 'Coding AI', pricing: 'Freemium', url: 'https://www.tabnine.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Tabnine_Logo.png', features: ['Private model training', 'Local execution mode', 'Team-specific knowledge', 'Enterprise-grade security'], pros: ['Excellent privacy and security', 'Works offline (local mode)', 'Low latency completions'], cons: ['Free tier is very limited', 'Less "chatty" than competitors', 'Setup can be complex'], rating: 4.5, reviewCount: 32000, popularity: 78, addedDate: '2013-01-01' },
  { id: 'amazon-q', name: 'Amazon Q', description: 'Generative AI-powered assistant for work that can be tailored to your business and code.', category: 'Coding AI', pricing: 'Freemium', url: 'https://aws.amazon.com/q/', logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg', features: ['AWS expert knowledge', 'Code transformation', 'Troubleshooting assistance', 'Enterprise data integration'], pros: ['Deep AWS ecosystem knowledge', 'Helps with cloud architecture', 'Secure and compliant'], cons: ['Mostly useful for AWS users', 'Can be complex to configure', 'Still in active development'], rating: 4.4, reviewCount: 2100, popularity: 70, addedDate: '2023-11-28' },
  { id: 'cody', name: 'Sourcegraph Cody', description: 'AI coding assistant that uses the context of your entire codebase to help you write and fix code.', category: 'Coding AI', pricing: 'Freemium', url: 'https://sourcegraph.com/cody', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Sourcegraph_Logo.png', rating: 4.6, reviewCount: 1800, popularity: 65, addedDate: '2023-05-01' },
  { id: 'replit-ghost', name: 'Replit AI', description: 'AI-powered suite of features for Replit that helps you write, explain, and debug code.', category: 'Coding AI', pricing: 'Paid', url: 'https://replit.com/site/ghostwriter', logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Replit_logo.svg', rating: 4.5, reviewCount: 15600, popularity: 100, addedDate: '2022-10-01' },
  { id: 'mutable', name: 'MutableAI', description: 'AI-accelerated software development platform for building high-quality code at scale.', category: 'Coding AI', pricing: 'Freemium', url: 'https://mutable.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Mutable_AI_Logo.png', rating: 4.2, reviewCount: 320, popularity: 45, addedDate: '2022-01-01' },
  { id: 'blackbox', name: 'Blackbox AI', description: 'AI coding assistant that helps you write code, find snippets, and build apps faster.', category: 'Coding AI', pricing: 'Freemium', url: 'https://www.useblackbox.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Blackbox_AI_Logo.png', rating: 4.3, reviewCount: 5400, popularity: 72, addedDate: '2021-01-01' },
  { id: 'askcodi', name: 'AskCodi', description: 'AI code assistant that provides tools for code generation, unit testing, and documentation.', category: 'Coding AI', pricing: 'Freemium', url: 'https://www.askcodi.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/AskCodi_Logo.png', rating: 4.1, reviewCount: 850, popularity: 55, addedDate: '2021-01-01' },
  { id: 'codiga', name: 'Codiga', description: 'Smart code analysis tool that helps developers write better code with real-time feedback.', category: 'Coding AI', pricing: 'Freemium', url: 'https://www.codiga.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Codiga_Logo.png', rating: 4.0, reviewCount: 420, popularity: 40, addedDate: '2020-01-01' },
  { id: 'bito', name: 'Bito', description: 'AI assistant that helps developers write code, explain concepts, and generate tests.', category: 'Coding AI', pricing: 'Freemium', url: 'https://bito.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Bito_AI_Logo.png', rating: 4.4, reviewCount: 2300, popularity: 62, addedDate: '2022-01-01' },
  { id: 'pieces', name: 'Pieces', description: 'AI-powered tool for saving, enriching, and reusing code snippets across your workflow.', category: 'Coding AI', pricing: 'Free', url: 'https://pieces.app', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Pieces_Logo.png', rating: 4.6, reviewCount: 1500, popularity: 58, addedDate: '2021-01-01' },
  { id: 'mintlify', name: 'Mintlify', description: 'AI tool that automatically generates beautiful documentation from your code.', category: 'Coding AI', pricing: 'Freemium', url: 'https://mintlify.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Mintlify_Logo.png', rating: 4.7, reviewCount: 2100, popularity: 68, addedDate: '2022-01-01' },
  { id: 'sourcery', name: 'Sourcery', description: 'AI-powered code refactoring tool that helps you write cleaner and more readable code.', category: 'Coding AI', pricing: 'Freemium', url: 'https://sourcery.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Sourcery_Logo.png', rating: 4.5, reviewCount: 1800, popularity: 52, addedDate: '2020-01-01' },
  { id: 'codium', name: 'CodiumAI', description: 'AI tool that generates meaningful test suites for your code to ensure quality and reliability.', category: 'Coding AI', pricing: 'Freemium', url: 'https://www.codium.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/CodiumAI_Logo.png', rating: 4.6, reviewCount: 2800, popularity: 64, addedDate: '2023-01-01' },

  // Voice AI
  { id: 'elevenlabs', name: 'ElevenLabs', description: 'Prime AI text-to-speech and voice cloning software for creators and publishers.', category: 'Voice AI', pricing: 'Freemium', url: 'https://elevenlabs.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/ElevenLabs_Logo.png', features: ['Instant voice cloning', 'Professional voice cloning', 'Speech-to-speech', 'Dubbing studio', 'API access'], pros: ['Best-in-class emotional range', 'Extremely fast generation', 'Huge library of community voices'], cons: ['Can be expensive for long-form content', 'Strict character limits on free tier', 'Voice cloning can be misused'], rating: 4.9, reviewCount: 15600, popularity: 100, addedDate: '2022-10-01' },
  { id: 'playht', name: 'PlayHT', description: 'AI Voice Generator with 900+ AI voices and realistic text-to-speech capabilities.', category: 'Voice AI', pricing: 'Freemium', url: 'https://play.ht', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/PlayHT_Logo.png', features: ['907+ AI voices', '142 languages', 'Voice cloning', 'Multi-voice editor'], pros: ['Massive variety of voices', 'Excellent for long-form articles', 'Great API for developers'], cons: ['Interface can be slightly complex', 'Quality varies between older voices', 'Free tier is quite restrictive'], rating: 4.7, reviewCount: 5400, popularity: 82, addedDate: '2016-01-01' },
  { id: 'murf', name: 'Murf AI', description: 'Versatile AI voice generator that allows you to create studio-quality voiceovers in minutes.', category: 'Voice AI', pricing: 'Freemium', url: 'https://murf.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Murf_AI_Logo.png', features: ['Studio-quality voices', 'Voice changer', 'Time-sync with video', 'Team collaboration'], pros: ['Professional-grade output', 'Built-in video editor', 'Great for corporate presentations'], cons: ['Limited voice styles', 'Subscription is relatively high', 'Free tier doesn\'t allow downloads'], rating: 4.6, reviewCount: 3200, popularity: 100, addedDate: '2020-01-01' },
  { id: 'speechify', name: 'Speechify', description: 'Leading text-to-speech app that turns any text into natural-sounding audio.', category: 'Voice AI', pricing: 'Freemium', url: 'https://speechify.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Speechify_Logo.png', features: ['OCR (Scan printed text)', 'Speed control (up to 9x)', 'Celebrity voices (Snoop Dogg, Gwyneth Paltrow)', 'Cross-device sync'], pros: ['Incredible for accessibility', 'High-quality celebrity voices', 'Excellent mobile app'], cons: ['Premium is very expensive', 'Some voices sound robotic at high speeds', 'Limited features on free version'], rating: 4.8, reviewCount: 45000, popularity: 88, addedDate: '2017-01-01' },
  { id: 'resemble', name: 'Resemble.ai', description: 'AI voice generator that creates human-like voices and allows for real-time voice cloning.', category: 'Voice AI', pricing: 'Freemium', url: 'https://www.resemble.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Resemble_AI_Logo.png', rating: 4.5, reviewCount: 1200, popularity: 65, addedDate: '2019-01-01' },
  { id: 'wellsaid', name: 'WellSaid Labs', description: 'Enterprise-grade AI voice platform for creating high-quality voiceovers for business.', category: 'Voice AI', pricing: 'Paid', url: 'https://wellsaidlabs.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/WellSaid_Labs_Logo.png', rating: 4.7, reviewCount: 850, popularity: 72, addedDate: '2018-01-01' },
  { id: 'lovo', name: 'Lovo.ai', description: 'Award-winning AI voice generator and text-to-speech platform with 500+ voices.', category: 'Voice AI', pricing: 'Freemium', url: 'https://lovo.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Lovo_AI_Logo.png', rating: 4.6, reviewCount: 2300, popularity: 75, addedDate: '2019-01-01' },
  { id: 'listnr', name: 'Listnr', description: 'AI voice generator that turns text into high-quality audio for podcasts and videos.', category: 'Voice AI', pricing: 'Freemium', url: 'https://www.listnr.tech', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Listnr_Logo.png', rating: 4.4, reviewCount: 420, popularity: 60, addedDate: '2020-01-01' },
  { id: 'voicemaker', name: 'Voicemaker', description: 'Professional text-to-speech converter with a wide range of voices and customization options.', category: 'Voice AI', pricing: 'Freemium', url: 'https://voicemaker.in', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Voicemaker_Logo.png', rating: 4.3, reviewCount: 1500, popularity: 68, addedDate: '2019-01-01' },
  { id: 'uberduck', name: 'Uberduck', description: 'AI voice platform for creators, featuring celebrity voices and text-to-speech tools.', category: 'Voice AI', pricing: 'Freemium', url: 'https://uberduck.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Uberduck_Logo.png', rating: 4.5, reviewCount: 2100, popularity: 74, addedDate: '2020-01-01' },
  { id: 'fakeyou', name: 'FakeYou', description: 'Community-driven AI voice platform with thousands of voices from movies and games.', category: 'Voice AI', pricing: 'Free', url: 'https://fakeyou.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/FakeYou_Logo.png', rating: 4.2, reviewCount: 5400, popularity: 80, addedDate: '2021-01-01' },
  { id: 'kits', name: 'Kits.ai', description: 'AI voice platform for musicians, offering high-quality voice cloning and conversion.', category: 'Voice AI', pricing: 'Freemium', url: 'https://www.kits.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Kits_Logo.png', rating: 4.7, reviewCount: 1800, popularity: 58, addedDate: '2023-01-01' },
  { id: 'rask', name: 'Rask.ai', description: 'AI video localization tool that translates and dubs videos in over 130 languages.', category: 'Voice AI', pricing: 'Paid', url: 'https://www.rask.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Rask_Logo.png', rating: 4.8, reviewCount: 2800, popularity: 62, addedDate: '2023-01-01' },
  { id: 'dubverse', name: 'Dubverse', description: 'AI video dubbing platform that helps you reach global audiences with ease.', category: 'Voice AI', pricing: 'Freemium', url: 'https://dubverse.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Dubverse_Logo.png', rating: 4.5, reviewCount: 1200, popularity: 55, addedDate: '2022-01-01' },
  { id: 'voicemod', name: 'Voicemod', description: 'Real-time AI voice changer and soundboard for gamers and content creators.', category: 'Voice AI', pricing: 'Freemium', url: 'https://www.voicemod.net', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Voicemod_Logo.png', features: ['Real-time voice changing', 'Soundboard', 'AI voice creator', 'Integration with Discord/OBS'], pros: ['Low latency for gaming', 'Huge library of fun voices', 'Easy to set up'], cons: ['Can be buggy with some drivers', 'Pro version is a subscription', 'Some voices sound very artificial'], rating: 4.6, reviewCount: 25000, popularity: 85, addedDate: '2014-01-01' },
  { id: 'descript-overdub', name: 'Descript Overdub', description: 'AI voice cloning feature in Descript that allows you to edit audio by typing.', category: 'Voice AI', pricing: 'Freemium', url: 'https://www.descript.com/overdub', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Descript_Logo.png', rating: 4.7, reviewCount: 3400, popularity: 70, addedDate: '2020-01-01' },

  // Productivity AI
  { id: 'notion-ai', name: 'Notion AI', description: 'Integrated AI tools within Notion to help you write, summarize, and brainstorm.', category: 'Productivity AI', pricing: 'Paid', url: 'https://www.notion.so/product/ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png', features: ['AI writing assistant', 'Database autofill', 'Meeting summaries', 'Q&A with your workspace'], pros: ['Seamlessly built into Notion', 'Excellent for brainstorming', 'Saves time on documentation'], cons: ['Requires Notion subscription + AI add-on', 'Can be slower than standalone LLMs', 'Limited advanced customization'], rating: 4.8, reviewCount: 125000, popularity: 100, addedDate: '2023-02-22' },
  { id: 'perplexity', name: 'Perplexity AI', description: 'AI-powered search engine that provides direct answers with cited sources.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://www.perplexity.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Perplexity_AI_logo.svg', features: ['Real-time web search', 'Source citations', 'File upload analysis', 'Pro Search with GPT-4/Claude 3'], pros: ['Extremely accurate for research', 'Transparent citations', 'Fast and clean interface'], cons: ['Free tier has daily Pro limits', 'Can occasionally miss context', 'Not for creative writing'], rating: 4.9, reviewCount: 84000, popularity: 100, addedDate: '2022-12-01' },
  { id: 'gamma', name: 'Gamma', description: 'A new medium for presenting ideas, powered by AI. Create beautiful presentations and docs in seconds.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://gamma.app', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Gamma_App_Logo.png', features: ['AI presentation generator', 'Responsive layouts', 'Interactive embeds', 'One-click styling'], pros: ['Stunning design quality', 'Much faster than PowerPoint', 'Great for web-based sharing'], cons: ['Limited export options on free tier', 'Can be hard to fine-tune specific details', 'Requires internet connection'], rating: 4.7, reviewCount: 12500, popularity: 85, addedDate: '2023-03-01' },
  { id: 'jasper', name: 'Jasper', description: 'AI content platform that helps teams create high-quality content for marketing and business.', category: 'Productivity AI', pricing: 'Paid', url: 'https://www.jasper.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Jasper_AI_Logo.png', features: ['Brand voice training', 'Campaign workflows', 'Art generation', 'SEO mode integration'], pros: ['Excellent for marketing teams', 'Strong focus on brand consistency', 'Comprehensive set of templates'], cons: ['Relatively expensive', 'Steep learning curve', 'Can produce generic content if not guided'], rating: 4.6, reviewCount: 8900, popularity: 100, addedDate: '2021-01-01' },
  { id: 'otter', name: 'Otter.ai', description: 'AI meeting assistant that transcribes conversations in real-time and generates summaries.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://otter.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Otter.ai_Logo.png', features: ['Real-time transcription', 'Automated meeting notes', 'Speaker identification', 'Calendar integration'], pros: ['Very accurate transcription', 'Great for remote team meetings', 'Easy to search through past meetings'], cons: ['Free tier has strict monthly limits', 'Struggles with heavy accents', 'Privacy concerns for sensitive meetings'], rating: 4.7, reviewCount: 15600, popularity: 84, addedDate: '2016-01-01' },
  { id: 'grammarly', name: 'Grammarly', description: 'AI-powered writing assistant that helps you write clearly and effectively across all platforms.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://www.grammarly.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Grammarly_logo.svg', features: ['Grammar & spell check', 'Tone detection', 'Plagiarism checker', 'AI generative writing'], pros: ['Works everywhere (browser, desktop, mobile)', 'Highly accurate suggestions', 'Great for professional communication'], cons: ['Premium is expensive', 'Can be overly prescriptive', 'Privacy concerns for sensitive data'], rating: 4.8, reviewCount: 250000, popularity: 100, addedDate: '2009-01-01' },
  { id: 'quillbot', name: 'Quillbot', description: 'AI paraphrasing tool that helps you rewrite and enhance your sentences and paragraphs.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://quillbot.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Quillbot_Logo.png', rating: 4.6, reviewCount: 18400, popularity: 90, addedDate: '2017-01-01' },
  { id: 'copy-ai', name: 'Copy.ai', description: 'AI writing platform for marketing and sales teams to generate high-converting copy.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://www.copy.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Copy.ai_Logo.png', rating: 4.5, reviewCount: 6300, popularity: 82, addedDate: '2020-01-01' },
  { id: 'writesonic', name: 'Writesonic', description: 'AI writing tool for creating SEO-friendly content, ads, and product descriptions.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://writesonic.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Writesonic_Logo.png', rating: 4.5, reviewCount: 5400, popularity: 78, addedDate: '2020-01-01' },
  { id: 'rytr', name: 'Rytr', description: 'AI writing assistant that helps you create high-quality content in seconds at a fraction of the cost.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://rytr.me', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Rytr_Logo.png', rating: 4.4, reviewCount: 3200, popularity: 75, addedDate: '2021-01-01' },
  { id: 'anyword', name: 'Anyword', description: 'AI writing platform for marketing teams that predicts performance and optimizes copy.', category: 'Productivity AI', pricing: 'Paid', url: 'https://anyword.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Anyword_Logo.png', rating: 4.6, reviewCount: 1200, popularity: 65, addedDate: '2013-01-01' },
  { id: 'surferseo', name: 'SurferSEO', description: 'AI-powered SEO tool that helps you optimize your content for search engine rankings.', category: 'Productivity AI', pricing: 'Paid', url: 'https://surferseo.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/SurferSEO_Logo.png', rating: 4.7, reviewCount: 2300, popularity: 70, addedDate: '2017-01-01' },
  { id: 'mem', name: 'Mem', description: 'AI-powered workspace that organizes your notes, tasks, and projects automatically.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://mem.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Mem_AI_Logo.png', rating: 4.5, reviewCount: 850, popularity: 60, addedDate: '2019-01-01' },
  { id: 'taskade', name: 'Taskade', description: 'AI-powered productivity platform for teams to manage tasks, projects, and notes.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://www.taskade.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Taskade_Logo.png', rating: 4.6, reviewCount: 1500, popularity: 68, addedDate: '2017-01-01' },
  { id: 'clickup-ai', name: 'ClickUp AI', description: 'AI assistant integrated into ClickUp to help you manage projects and write content.', category: 'Productivity AI', pricing: 'Paid', url: 'https://clickup.com/ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/ClickUp_Logo.png', rating: 4.5, reviewCount: 2800, popularity: 80, addedDate: '2023-01-01' },
  { id: 'fireflies', name: 'Fireflies.ai', description: 'AI meeting assistant that records, transcribes, and searches your voice conversations.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://fireflies.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Fireflies_AI_Logo.png', rating: 4.7, reviewCount: 4200, popularity: 74, addedDate: '2018-01-01' },
  { id: 'krisp', name: 'Krisp', description: 'AI-powered noise cancellation app that removes background noise from your calls.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://krisp.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Krisp_Logo.png', features: ['Bi-directional noise removal', 'Acoustic echo cancellation', 'Voice productivity insights', 'Call summaries'], pros: ['Magic-like noise removal', 'Works with any headset', 'Privacy-first (local processing)'], cons: ['Free tier is very limited', 'Can use significant CPU', 'Occasional voice distortion'], rating: 4.8, reviewCount: 12400, popularity: 82, addedDate: '2017-01-01' },
  { id: 'rewind', name: 'Rewind', description: 'The search engine for your life, allowing you to find anything you\'ve seen, said, or heard.', category: 'Productivity AI', pricing: 'Paid', url: 'https://www.rewind.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Rewind_Logo.png', rating: 4.7, reviewCount: 540, popularity: 55, addedDate: '2023-01-01' },

  // Marketing AI
  { id: 'adcreative', name: 'AdCreative.ai', description: 'Generate conversion-focused ad creatives and social media posts in seconds.', category: 'Marketing AI', pricing: 'Paid', url: 'https://www.adcreative.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/AdCreative_AI_Logo.png', features: ['Ad creative generation', 'Social media post generator', 'Competitor analysis', 'Performance prediction'], pros: ['Highly data-driven', 'Saves hours on design', 'Great for scaling ad campaigns'], cons: ['No free tier', 'Designs can feel repetitive', 'Steep learning curve for some features'], rating: 4.6, reviewCount: 3200, popularity: 75, addedDate: '2021-01-01' },
  { id: 'pencil', name: 'Pencil', description: 'AI-powered creative platform for e-commerce brands to generate winning video ads.', category: 'Marketing AI', pricing: 'Paid', url: 'https://www.trypencil.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Pencil_AI_Logo.png', rating: 4.5, reviewCount: 1200, popularity: 68, addedDate: '2020-01-01' },
  { id: 'phrasee', name: 'Phrasee', description: 'AI platform that optimizes marketing copy for email, social media, and push notifications.', category: 'Marketing AI', pricing: 'Paid', url: 'https://phrasee.co', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Phrasee_Logo.png', rating: 4.7, reviewCount: 850, popularity: 62, addedDate: '2015-01-01' },
  { id: 'marketmuse', name: 'MarketMuse', description: 'AI content planning and optimization platform for building topical authority.', category: 'Marketing AI', pricing: 'Paid', url: 'https://www.marketmuse.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/41/MarketMuse_Logo.png', rating: 4.6, reviewCount: 2300, popularity: 60, addedDate: '2013-01-01' },

  // Design AI
  { id: 'uizard', name: 'Uizard', description: 'AI-powered design tool for creating wireframes, mockups, and prototypes in minutes.', category: 'Design AI', pricing: 'Freemium', url: 'https://uizard.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Uizard_Logo.png', features: ['Sketch-to-design', 'Screenshot-to-design', 'AI UI generator', 'Collaboration tools'], pros: ['Incredibly fast prototyping', 'Great for non-designers', 'Intuitive drag-and-drop'], cons: ['Limited export formats', 'Can be buggy with complex sketches', 'Paid plan needed for full features'], rating: 4.7, reviewCount: 8400, popularity: 78, addedDate: '2018-01-01' },
  { id: 'galileo', name: 'Galileo AI', description: 'Generative AI for interface design that turns text prompts into high-fidelity UI designs.', category: 'Design AI', pricing: 'Paid', url: 'https://www.usegalileo.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Galileo_AI_Logo.png', rating: 4.8, reviewCount: 1500, popularity: 65, addedDate: '2023-01-01' },
  { id: 'khroma', name: 'Khroma', description: 'AI color tool for designers that learns your preferences to create infinite palettes.', category: 'Design AI', pricing: 'Free', url: 'https://www.khroma.co', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Khroma_Logo.png', rating: 4.4, reviewCount: 32000, popularity: 58, addedDate: '2018-01-01' },
  { id: 'fontjoy', name: 'Fontjoy', description: 'AI tool that helps designers find perfect font pairings using deep learning.', category: 'Design AI', pricing: 'Free', url: 'https://fontjoy.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Fontjoy_Logo.png', rating: 4.5, reviewCount: 12500, popularity: 62, addedDate: '2017-01-01' },

  // Writing AI
  { id: 'sudowrite', name: 'Sudowrite', description: 'The AI writing partner for fiction authors, helping with brainstorming and drafting.', category: 'Writing AI', pricing: 'Paid', url: 'https://www.sudowrite.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Sudowrite_Logo.png', features: ['Story Engine', 'Sensory descriptions', 'Rewrite tool', 'Brainstorming mode'], pros: ['Specifically built for fiction', 'Excellent creative suggestions', 'Helps overcome writer\'s block'], cons: ['No free tier', 'Can be expensive for high word counts', 'Steep learning curve for Story Engine'], rating: 4.8, reviewCount: 4200, popularity: 72, addedDate: '2020-01-01' },
  { id: 'wordtune', name: 'Wordtune', description: 'AI writing assistant that helps you rephrase and rewrite your thoughts for clarity.', category: 'Writing AI', pricing: 'Freemium', url: 'https://www.wordtune.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Wordtune_Logo.png', rating: 4.7, reviewCount: 15600, popularity: 85, addedDate: '2020-01-01' },
  { id: 'hemingway', name: 'Hemingway Editor Plus', description: 'AI-powered editor that makes your writing bold and clear by fixing complex sentences.', category: 'Writing AI', pricing: 'Paid', url: 'https://hemingwayapp.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Hemingway_Editor_Logo.png', rating: 4.5, reviewCount: 2100, popularity: 68, addedDate: '2023-01-01' },
  { id: 'pro-writing-aid', name: 'ProWritingAid', description: 'Comprehensive AI writing assistant for grammar, style, and creative writing analysis.', category: 'Writing AI', pricing: 'Freemium', url: 'https://prowritingaid.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/ProWritingAid_Logo.png', rating: 4.6, reviewCount: 8900, popularity: 74, addedDate: '2012-01-01' },

  // Data AI
  { id: 'polymer', name: 'Polymer', description: 'AI tool that turns your spreadsheets into searchable, interactive, and beautiful databases.', category: 'Data AI', pricing: 'Paid', url: 'https://www.polymersearch.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Polymer_Search_Logo.png', rating: 4.6, reviewCount: 1200, popularity: 58, addedDate: '2019-01-01' },
  { id: 'akkio', name: 'Akkio', description: 'No-code AI platform for generative business analytics and predictive modeling.', category: 'Data AI', pricing: 'Paid', url: 'https://www.akkio.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Akkio_Logo.png', rating: 4.7, reviewCount: 850, popularity: 52, addedDate: '2019-01-01' },
  { id: 'tableau-ai', name: 'Tableau AI', description: 'Generative AI integrated into Tableau for faster data preparation and insight discovery.', category: 'Data AI', pricing: 'Paid', url: 'https://www.tableau.com/products/ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Tableau_Logo.svg', features: ['Natural language queries', 'Automated insights', 'Data storytelling', 'Predictive analytics'], pros: ['Industry-leading visualization', 'Powerful data processing', 'Great for enterprise teams'], cons: ['Very expensive', 'High technical barrier', 'Requires structured data'], rating: 4.8, reviewCount: 45000, popularity: 85, addedDate: '2023-01-01' },
  { id: 'monkeylearn', name: 'MonkeyLearn', description: 'No-code text analysis platform that uses AI to extract insights from your data.', category: 'Data AI', pricing: 'Paid', url: 'https://monkeylearn.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/MonkeyLearn_Logo.png', rating: 4.5, reviewCount: 2300, popularity: 60, addedDate: '2014-01-01' },

  // Music AI
  { id: 'suno', name: 'Suno AI', description: 'Breakthrough AI model that creates full songs with vocals and instrumentation from text.', category: 'Music AI', pricing: 'Freemium', url: 'https://suno.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Suno_AI_logo.png', features: ['Full song generation', 'Custom lyrics', 'Style/Genre selection', 'Vocal/Instrumental control'], pros: ['Incredible vocal quality', 'Very easy to use', 'Supports many genres'], cons: ['Limited control over specific notes', 'Copyright ownership can be complex', 'Free tier has daily limits'], rating: 4.9, reviewCount: 54000, popularity: 92, addedDate: '2023-12-01' },
  { id: 'udio', name: 'Udio', description: 'Advanced AI music generation platform known for high-fidelity and expressive vocals.', category: 'Music AI', pricing: 'Freemium', url: 'https://www.udio.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Udio_Logo.png', rating: 4.8, reviewCount: 12500, popularity: 88, addedDate: '2024-04-10' },
  { id: 'soundraw', name: 'Soundraw', description: 'AI music generator for creators that allows you to customize songs to fit your content.', category: 'Music AI', pricing: 'Freemium', url: 'https://soundraw.io', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Soundraw_Logo.png', rating: 4.6, reviewCount: 8400, popularity: 75, addedDate: '2020-01-01' },
  { id: 'mubert', name: 'Mubert', description: 'AI-powered music ecosystem for creators and brands to generate royalty-free music.', category: 'Music AI', pricing: 'Freemium', url: 'https://mubert.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Mubert_Logo.png', rating: 4.5, reviewCount: 15600, popularity: 70, addedDate: '2017-01-01' },

  // Education AI
  { id: 'khanmigo', name: 'Khanmigo', description: 'AI-powered tutor by Khan Academy that helps students with learning and teachers with planning.', category: 'Education AI', pricing: 'Paid', url: 'https://www.khanacademy.org/khanmigo', logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Khan_Academy_logo.svg', features: ['Socratic tutoring', 'Lesson planning', 'Writing feedback', 'Coding assistance'], pros: ['Safe for children', 'Pedagogically sound', 'Great for personalized learning'], cons: ['Requires monthly donation/fee', 'Sometimes too restrictive', 'Limited to Khan Academy content'], rating: 4.8, reviewCount: 6300, popularity: 85, addedDate: '2023-03-01' },
  { id: 'duolingo-max', name: 'Duolingo Max', description: 'Premium Duolingo tier with AI features like "Explain My Answer" and "Roleplay".', category: 'Education AI', pricing: 'Paid', url: 'https://www.duolingo.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Duolingo_logo.svg', rating: 4.7, reviewCount: 125000, popularity: 92, addedDate: '2023-03-01' },
  { id: 'elicit', name: 'Elicit', description: 'AI research assistant that helps you find and summarize academic papers efficiently.', category: 'Education AI', pricing: 'Freemium', url: 'https://elicit.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Elicit_Logo.png', rating: 4.8, reviewCount: 18400, popularity: 78, addedDate: '2021-01-01' },
  { id: 'consensus', name: 'Consensus', description: 'AI search engine that finds answers in scientific research papers and provides evidence.', category: 'Education AI', pricing: 'Freemium', url: 'https://consensus.app', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Consensus_Logo.png', rating: 4.7, reviewCount: 5400, popularity: 74, addedDate: '2022-01-01' },
  { id: 'flux', name: 'Flux.1', description: 'Next-generation open-weights image generation model by Black Forest Labs.', category: 'Image Generation', pricing: 'Free', url: 'https://blackforestlabs.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Flux_AI_Logo.png', rating: 4.9, reviewCount: 1200, popularity: 96, addedDate: '2024-08-01' },
  { id: 'kling', name: 'Kling AI', description: 'Advanced video generation model capable of creating high-fidelity cinematic videos.', category: 'Video AI', pricing: 'Freemium', url: 'https://klingai.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Kling_AI_Logo.png', rating: 4.8, reviewCount: 850, popularity: 92, addedDate: '2024-07-15' },
  { id: 'grok-2', name: 'Grok-2', description: 'The latest frontier model from xAI with enhanced reasoning and image generation.', category: 'Chat AI', pricing: 'Paid', url: 'https://x.ai', logo: 'https://upload.wikimedia.org/wikipedia/commons/5/57/X_logo_2023_%28white%29.svg', rating: 4.7, reviewCount: 2100, popularity: 100, addedDate: '2024-08-14' },
  { id: 'zapier', name: 'Zapier Central', description: 'AI-powered automation platform that lets you build custom AI agents to automate your work across 6,000+ apps.', category: 'Productivity AI', pricing: 'Freemium', url: 'https://zapier.com/central', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Zapier_logo.svg', rating: 4.8, reviewCount: 15000, popularity: 100, addedDate: '2024-03-01' },
];

// Add 276 more tools
const categories: Category[] = ['Chat AI', 'Image Generation', 'Video AI', 'Coding AI', 'Voice AI', 'Productivity AI', 'Marketing AI', 'Design AI', 'Writing AI', 'Data AI', 'Music AI', 'Education AI'];
const pricings: Pricing[] = ['Free', 'Freemium', 'Paid'];

for (let i = 1; i <= 276; i++) {
  const category = categories[i % categories.length];
  const pricing = pricings[i % pricings.length];
  const id = `tool-${i}`;
  const name = `${category.split(' ')[0]} Master ${i}`;
  
  const prosOptions = [
    ['Fast generation', 'High quality output', 'Easy to use'],
    ['Great for beginners', 'Good community support', 'Excellent documentation'],
    ['Powerful features', 'Highly customizable', 'Regular updates'],
    ['Mobile friendly', 'Clean interface', 'Good value for money'],
    ['Advanced AI models', 'Secure and private', 'Scalable solution']
  ];
  const consOptions = [
    ['Steep learning curve', 'Expensive subscription', 'Limited free tier'],
    ['Occasional bugs', 'Slow customer support', 'Missing some advanced features'],
    ['Requires high-end hardware', 'Internet connection required', 'Limited integrations'],
    ['Can be complex to set up', 'Interface can be cluttered', 'Limited customization'],
    ['New and evolving', 'Some features in beta', 'Knowledge base is growing']
  ];
  const useCaseOptions = [
    ['Personal Productivity', 'Academic Writing', 'Creative Design'],
    ['Business Automation', 'Data Analysis', 'Customer Support'],
    ['Software Development', 'Marketing Strategy', 'Video Production'],
    ['Language Learning', 'Financial Planning', 'Health & Wellness'],
    ['Social Media Management', 'E-commerce Optimization', 'Project Management']
  ];

  TOOLS_DATA.push({
    id,
    name,
    description: `A powerful ${category} tool designed to enhance your workflow and boost creativity with advanced AI algorithms.`,
    category,
    pricing,
    url: `https://example.com/${id}`,
    logo: `https://api.dicebear.com/7.x/shapes/svg?seed=${id}&backgroundColor=6366f1,4f46e5,4338ca,3730a3,312e81`,
    features: [`Feature A for ${category}`, `Feature B for ${category}`, 'Cloud Sync', 'API Access'],
    pros: prosOptions[i % prosOptions.length],
    cons: consOptions[i % consOptions.length],
    useCases: useCaseOptions[i % useCaseOptions.length],
    isVerified: i % 5 === 0,
    hasDeals: i % 7 === 0,
    tags: [category.split(' ')[0], 'AI', 'Tool'],
    rating: Number((3.5 + Math.random() * 1.5).toFixed(1)),
    reviewCount: Math.floor(Math.random() * 5000) + 50,
    popularity: Math.floor(Math.random() * 80),
    addedDate: new Date(2023, Math.floor(Math.random() * 12), Math.floor(Math.random() * 28) + 1).toISOString().split('T')[0]
  });
}
